server:
  port: 8089
  timeout: 120s
  sleep: 10s

network: mainnet

fullnode:
  btc:
    rpcs:
      - rpc_url:
        rpc_user:
        rpc_pass:
    confirmations: 1
  eth:
    rpcs:
      - rpc_url: 'https://mainnet.infura.io/v3/b48b6387e66d4f3497245873747f6e4d'
    confirmations: 4
  solana:
    public_api: 'https://public-api.solscan.io'

chains: [btc, eth, solana, trx]

