server:
  port: 8888
  timeout: 120s
  sleep: 10s

network: testnet

fullnode:
  btc:
    rpcs:
      - rpc_url:
        rpc_user:
        rpc_pass:
    confirmations: 1
  eth:
    rpcs:
      - rpc_url:
    confirmations: 4
  solana:
    public_api: 'https://public-api.solscan.io'
    NonceAccountAddr: DJyNpXgggw1WGgjTVzFsNjb3fuQZVMqhoakvSBfX9LYx
    FeeAccountPriKey: 4TMFNY9ntAn3CHzguSAvDNLPRoQTaK3sWbQQXdDXaE6KWRBLufGL6PJdsD2koiEe3gGmMdRK3aAw7sikGNksHJrN

chains: [btc, eth]

